# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gabor7669/Desktop/TFE4141/tfe4141_term_project_integration_kit_v2/term_project/term_project.srcs/sources_1/bd/rsa_soc/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0.xci
# IP: The module: 'rsa_soc_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gabor7669/Desktop/TFE4141/tfe4141_term_project_integration_kit_v2/term_project/term_project.srcs/sources_1/bd/rsa_soc/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rsa_soc_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/gabor7669/Desktop/TFE4141/tfe4141_term_project_integration_kit_v2/term_project/term_project.srcs/sources_1/bd/rsa_soc/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0.xci
# IP: The module: 'rsa_soc_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gabor7669/Desktop/TFE4141/tfe4141_term_project_integration_kit_v2/term_project/term_project.srcs/sources_1/bd/rsa_soc/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rsa_soc_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
